### ISSUE TITLE
COCOA/cocoa_cat_list

### ISSUE THREAD

**Issue by Championchess** [UARK-AICV/AISFormer#2]
Hello! Thanks for your nice work for amodal instance segmentation.

I have tried to run your code, but it seems that COCOA/cocoa_cat_list is missing so I cannot run it. Where can I find the file?

Also, could you please release you pretrained model on COCOA since it will be very useful to study amodal segmentation in the context of general object categories? 

Thanks again!

**Comment by trqminh** [comment]
Thank you for your interest in our work. You can use this script (https://github.com/UARK-AICV/AISFormer/blob/master/tools/get_cocoa_classes.py) to generate the cocoa_cat_list. 
Regarding the trained models, I try my best to release it soon, I'll remind you here when it is released.
