### ISSUE TITLE
About ASN reproduction

### ISSUE THREAD

**Issue by ZitengXue** [UARK-AICV/AISFormer#7]
Hi @trqminh !
Sorry to bother you again,I notice that you reproduced the ASN's code,I'm struggleing on it now,the environment of ASN is too old,I'm not sure how to set the envirment,is it convenient for you to release the reproduced code?A requirments.txt will also help!Thanks !!!!!!!

**Comment by trqminh** [comment]
Hi @ZitengXue ,
Actually I didn't rerun their code but reimplemented it on the current detectron2 version to reproduce. That code is quite a mess right now and I intend to clean it up and publish it to this [repo of ais methods](https://github.com/trqminh/aistron), or you can also refer on some other method that I reimplement there to reproduce ASN.

Hope this help!

**Comment by ZitengXue** [comment]
I see!! very very very thank you for your reply！！！！(*^▽^*)
