### ISSUE TITLE
How to generate ground truth masks of COCOA 

### ISSUE THREAD

**Issue by staple-pi** [UARK-AICV/AISFormer#8]
Hello! I'm a rookie to CV, and i'm trying to do some work about amodal segmentation. I had some problems about generate ground truth masks from annotation of COCOA. I try to use the amodalAPI of pycocotools provided by the author, but it seems based on python2.X which  caused me a lot of trouble. Can you tell me how to generate the ground truth masks? Thank you very much

**Comment by trqminh** [comment]
You could checkout my new toolbox on amodal segmentation, I have a document about [preparing and visualizing dataset](https://github.com/trqminh/aistron/tree/main/datasets#prepare-datasets-for-aistron)

**Comment by staple-pi** [comment]
> You could checkout my new toolbox on amodal segmentation, I have a document about [preparing and visualizing dataset](https://github.com/trqminh/aistron/tree/main/datasets#prepare-datasets-for-aistron)

Thank you  very much. I wish you all the best in your scientific research and work.
